version: '2.1'

services:
  mongo:
    image: mongo:3.6.4
    container_name: arrecadar-mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017 --quiet
      interval: 5s
      retries: 3
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: arrecadar
      MONGO_INITDB_ROOT_PASSWORD: secret

  base:
    build:
      context: .
      args:
        PRODUCTION: 'false'
    volumes:
      - ./server.js:/api/server.js
      - ./app:/api/app
      - ./bootstrap:/api/bootstrap
      - ./config:/api/config

  base-tests:
    extends: base
    volumes:
      - ./tests:/api/tests
      - ./.eslintrc.js:/api/.eslintrc.js

  api:
    extends: base
    container_name: arrecadar-api
    command: npm run dev
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      mongo:
        condition: service_healthy

  lint:
    extends: base-tests
    container_name: arrecadar-lint
    command: npm run lint

  test:
    extends: base-tests
    container_name: arrecadar-test
    command: npm run test
    links:
      - api

  test-unit:
    extends: base-tests
    container_name: arrecadar-test
    command: npm run test:unit

  test-integration:
    extends: base-tests
    container_name: arrecadar-test
    command: npm run test:integration
    links:
      - api

  test-functional:
    extends: base-tests
    container_name: arrecadar-test
    command: npm run test:functional
    links:
      - api
