version: 2

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Set Environment Variables
          command: cp .env.example .env
      - run:
          name: Build Docker Services
          command: docker-compose build
      - run:
          name: Run Linter
          command: docker-compose run --rm lint
      - run:
          name: Run Unit Tests
          command: docker-compose run --rm test-unit
      - run:
          name: Run Integration Tests
          command: docker-compose run --rm test-integration
      - run:
          name: Run Functional Tests
          command: docker-compose run --rm test-functional
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install-standalone.sh | sh
      - run:
          name: Sign into Container Registry
          command: heroku container:login
      - run:
          name: Push Dockerfile
          command: heroku container:push web --app=${HEROKU_APP_NAME}
      - run:
          name: Release
          command: heroku container:release web --app=${HEROKU_APP_NAME}

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
