version: 2

jobs:
  install:
    machine: true
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Set Environment Variables
          command: cp .env.example .env
      - run:
          name: Build Docker Services
          command: docker-compose build
      - run:
          name: Run Linter
          command: docker-compose run --rm lint
      - run:
          name: Run Unit Tests
          command: docker-compose run --rm test-unit
      - run:
          name: Run Integration Tests
          command: docker-compose run --rm test-integration
      - run:
          name: Run Functional Tests
          command: docker-compose run --rm test-functional

workflows:
  version: 2
  test-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
